config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  # get "tasks", to: "tasks#index"
  # post "/", to: "tasks#create"
  # get "tasks/new", to: "tasks#new"
  # get "tasks/edit", to: "tasks#edit"
  # get "tasks/:id", to: "tasks#show"
  # patch "tasks/:id", to: "tasks#update"
  # put "tasks/:id", to: "tasks#update"
  # delete "tasks/:id", to: "tasks#destroy"
  # resources :tasks, only: [:index, :show, :edit, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :destroy, :update]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
   @task = Task.new
  end

  def create
   Task.create(task_params)
   redirect_to tasks_path
  end

  def edit
    @task = Task.find(param[:id])
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :location, :priority)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_bananas.html.erb
<%= form_for @task do |f| %>

  <%= f.label :name, "Enter Name/Description" %>
  <%= f.text_field :name %>

  <%= f.label :location, "Enter task location" %>
  <%= f.text_field :location %>

  <%= f.label :priority, "Enter Priority" %>
  <%= f.text_field :priority %>

  <%= f.submit%>
<% end %>

app/views/tasks/edit.html.erb
<%= render "bananas" %>

app/views/tasks/index.html.erb
<h1>Showing all tasks</h1>

<% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <p><%= task.location %></p>
  <p><%= task.priority %></p>
  <%= link_to "More info", task_path(task) %>
  <%= link_to "Add new task", new_task_path  %>
  <%= link_to "Delete task", task_path(task), method: :delete %>
<% end %>

app/views/tasks/new.html.erb
<%= render "bananas" %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.location %></p>
<p><%= @task.priority %></p>

<%= link_to "List of tasks", tasks_path %>